// <auto-generated />
using System;
using EtsoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EtsoApi.Migrations
{
    [DbContext(typeof(EtsoDbContext))]
    [Migration("20260828075402_IslemKayitlariVeSistemYoneticisi")]
    partial class IslemKayitlariVeSistemYoneticisi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EtsoApi.Models.Ayar", b =>
                {
                    b.Property<string>("Anahtar")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Anahtar");

                    b.ToTable("Ayarlar");
                });

            modelBuilder.Entity("EtsoApi.Models.Esnaf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Derece")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DurumDegisimNedeni")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("DurumDegisimTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FaaliyetDetayi")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Gorevi")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("GorevliId")
                        .HasColumnType("int");

                    b.Property<int?>("GrupId")
                        .HasColumnType("int");

                    b.Property<string>("Il")
                        .HasColumnType("longtext");

                    b.Property<string>("Ilce")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("IsTelefonu")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Isletme")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("KurulusTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mahalle")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("NaceAdi")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NaceKodu")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("OdaKararTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Odendi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sermaye")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SirketTipi")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime?>("SonGorusmeTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TabelaUnvani")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TicaretSicilNo")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UyeSicilNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UyelikDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Uyruk")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("VergiDairesi")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("VergiNo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("VergiTerkTarihi")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Durum");

                    b.HasIndex("GorevliId");

                    b.HasIndex("GrupId");

                    b.HasIndex("UyeSicilNo")
                        .IsUnique();

                    b.HasIndex("UyelikDurumu");

                    b.ToTable("Esnaflar");
                });

            modelBuilder.Entity("EtsoApi.Models.EsnafYetkili", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("EsnafId")
                        .HasColumnType("int");

                    b.Property<string>("Gorevi")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime?>("YetkiBaslangic")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("YetkiBitis")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EsnafId");

                    b.ToTable("EsnafYetkilileri");
                });

            modelBuilder.Entity("EtsoApi.Models.Gorevlendirme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("EsnafId")
                        .HasColumnType("int");

                    b.Property<int>("GorevliId")
                        .HasColumnType("int");

                    b.Property<int?>("GrupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KararTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Not")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("RedMazereti")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EsnafId");

                    b.HasIndex("GorevliId");

                    b.HasIndex("GrupId");

                    b.ToTable("Gorevlendirmeler");
                });

            modelBuilder.Entity("EtsoApi.Models.Gorusme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EsnafId")
                        .HasColumnType("int");

                    b.Property<int>("GorevliId")
                        .HasColumnType("int");

                    b.Property<int?>("IkinciGorevliId")
                        .HasColumnType("int");

                    b.Property<string>("Not")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<string>("Sonuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("TakipGerekli")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EsnafId");

                    b.HasIndex("GorevliId");

                    b.HasIndex("IkinciGorevliId");

                    b.HasIndex("Tarih");

                    b.ToTable("Gorusmeler");
                });

            modelBuilder.Entity("EtsoApi.Models.Grup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("No")
                        .HasColumnType("int");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("UstGrupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.HasIndex("No")
                        .IsUnique();

                    b.HasIndex("UstGrupId");

                    b.ToTable("Gruplar");
                });

            modelBuilder.Entity("EtsoApi.Models.IslemKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detay")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("EsnafId")
                        .HasColumnType("int");

                    b.Property<string>("EsnafUnvan")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("KullaniciAdSoyad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EsnafId");

                    b.HasIndex("Tarih");

                    b.ToTable("IslemKayitlari");
                });

            modelBuilder.Entity("EtsoApi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("BasarisizGiris")
                        .HasColumnType("int");

                    b.Property<string>("Birim")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Eposta")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Gorev")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime?>("KilitBitis")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("SifreGuncelleme")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SifreHash")
                        .HasColumnType("longtext");

                    b.Property<bool>("SistemYoneticisi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("EtsoApi.Models.KullaniciGrup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("Sira")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupId");

                    b.HasIndex("KullaniciId", "GrupId")
                        .IsUnique();

                    b.ToTable("KullaniciGruplari");
                });

            modelBuilder.Entity("EtsoApi.Models.Onay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("EsnafId")
                        .HasColumnType("int");

                    b.Property<int?>("GorevliId")
                        .HasColumnType("int");

                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Durum");

                    b.HasIndex("EsnafId");

                    b.HasIndex("GorevliId");

                    b.ToTable("Onaylar");
                });

            modelBuilder.Entity("EtsoApi.Models.Esnaf", b =>
                {
                    b.HasOne("EtsoApi.Models.Kullanici", "Gorevli")
                        .WithMany()
                        .HasForeignKey("GorevliId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EtsoApi.Models.Grup", "Grup")
                        .WithMany("Esnaflar")
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Gorevli");

                    b.Navigation("Grup");
                });

            modelBuilder.Entity("EtsoApi.Models.EsnafYetkili", b =>
                {
                    b.HasOne("EtsoApi.Models.Esnaf", "Esnaf")
                        .WithMany("Yetkililer")
                        .HasForeignKey("EsnafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Esnaf");
                });

            modelBuilder.Entity("EtsoApi.Models.Gorevlendirme", b =>
                {
                    b.HasOne("EtsoApi.Models.Esnaf", "Esnaf")
                        .WithMany()
                        .HasForeignKey("EsnafId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EtsoApi.Models.Kullanici", "Gorevli")
                        .WithMany()
                        .HasForeignKey("GorevliId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EtsoApi.Models.Grup", "Grup")
                        .WithMany()
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Esnaf");

                    b.Navigation("Gorevli");

                    b.Navigation("Grup");
                });

            modelBuilder.Entity("EtsoApi.Models.Gorusme", b =>
                {
                    b.HasOne("EtsoApi.Models.Esnaf", "Esnaf")
                        .WithMany("Gorusmeler")
                        .HasForeignKey("EsnafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtsoApi.Models.Kullanici", "Gorevli")
                        .WithMany()
                        .HasForeignKey("GorevliId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EtsoApi.Models.Kullanici", "IkinciGorevli")
                        .WithMany()
                        .HasForeignKey("IkinciGorevliId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Esnaf");

                    b.Navigation("Gorevli");

                    b.Navigation("IkinciGorevli");
                });

            modelBuilder.Entity("EtsoApi.Models.Grup", b =>
                {
                    b.HasOne("EtsoApi.Models.Grup", "UstGrup")
                        .WithMany()
                        .HasForeignKey("UstGrupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UstGrup");
                });

            modelBuilder.Entity("EtsoApi.Models.KullaniciGrup", b =>
                {
                    b.HasOne("EtsoApi.Models.Grup", "Grup")
                        .WithMany("Calisanlar")
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtsoApi.Models.Kullanici", "Kullanici")
                        .WithMany("Gruplar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grup");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EtsoApi.Models.Onay", b =>
                {
                    b.HasOne("EtsoApi.Models.Esnaf", "Esnaf")
                        .WithMany()
                        .HasForeignKey("EsnafId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EtsoApi.Models.Kullanici", "Gorevli")
                        .WithMany()
                        .HasForeignKey("GorevliId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Esnaf");

                    b.Navigation("Gorevli");
                });

            modelBuilder.Entity("EtsoApi.Models.Esnaf", b =>
                {
                    b.Navigation("Gorusmeler");

                    b.Navigation("Yetkililer");
                });

            modelBuilder.Entity("EtsoApi.Models.Grup", b =>
                {
                    b.Navigation("Calisanlar");

                    b.Navigation("Esnaflar");
                });

            modelBuilder.Entity("EtsoApi.Models.Kullanici", b =>
                {
                    b.Navigation("Gruplar");
                });
#pragma warning restore 612, 618
        }
    }
}
